import { Inter } from "next/font/google";
import Link from "next/link"
import Drawer from "./utils/drawer.jsx"
import "./globals.css";

import Image from "next/image";
import logo from "./assets/logo.png";

const inter = Inter({ subsets: ["latin"] });

export 
const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const list = ["/", "/about_us", "/projects", "/contact"];

  return (
    <html lang="en">
      <body className="">
        <div className="flex flex-row justify-between px-2 w-full h-[50px] "> 
             <Link href="/" >
                 <Image 
              src= {logo}
              width={80}
              height={40}
              className="object-contain"
              alt="logo icon"
              />
              </Link>
              <Drawer nav_list={list}/>
              {/*destop menu */}
              <div className="flex justify-between items-center w-[50%] max-md:hidden">
                <Link
                  href="/" className="hover:bg-slate-200 focus:ring-2 focus:ring-slate-500"
                ><div>Home</div></Link>
                <Link href={"/about_us"} className="hover:bg-slate-200 focus:ring-2 focus:ring-slate-500"><div>About Us</div></Link>
                <Link href="/projects" className="hover:bg-slate-200 focus:ring-2 focus:ring-slate-500"><div>Projects</div></Link>
                <Link href="/contact" className="hover:bg-slate-200 focus:ring-2 focus:ring-slate-500"><div>Contact</div></Link>
              </div>
        </div>
        {children}
        </body>
    </html>
  );
}
